<?php

$form->setAttribute( "action", 
	$this->url( "user", [ "action" => "add" ] ) );

$id = $form->get( "id" );
$email = $form->get( "email" );
$passwd = $form->get( "passwd" );
$passwd_confirm = $form->get( "passwd_confirm" );
$captcha = $form->get( "re_captcha" );
$remember_me = $form->get( "remember_me" );
$csrf_security = $form->get( "csrf_security" );
$submit_button = $form->get( "submit_button" );

$form->prepare() ?>

			<?= $this->form()->openTag( $form ), "\n" ?>
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>

				<div class="input-group mb-2 mb-sm-0">
    			<div class="input-group-addon">@</div>
					<?= $this->formEmail( $email ), "\n" ?>
				</div>
				<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
				<?= $this->userRegistrationElementError( $email ) ?>

        <label for="inputPassword" class="sr-only">Password</label>

				<?= $this->formPassword( $passwd ), "\n" ?>

				<?= $this->userRegistrationElementError( $email ) ?>

        <label for="inputPassword" class="sr-only">Repeat Password</label>
				<?= $this->formPassword( $passwd_confirm ), "\n" ?>

				<?= $this->userRegistrationElementError( $passwd_confirm ) ?>

				<?= $this->formCaptcha( $captcha ), "\n" ?>

				<?= $this->userRegistrationElementError( $captcha ) ?>

        <div class="checkbox">
						<?= $this->formCheckbox( $remember_me ), "Remember me", "\n" ?>
        </div>

				<?= $this->formSubmit( $submit_button ), "\n" ?>

				<?= $this->formHidden( $id ), "\n" ?>

				<?= $this->formElement( $csrf_security ), "\n" ?>

			<?= $this->form()->closeTag(), "\n" ?>

    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../../../assets/js/ie10-viewport-bug-workaround.js"></script>
